language: android
android:
  components:
  - tools
  - platform-tools
  - tools
  - build-tools-27.0.3
  - build-tools-26.0.2
  - android-27
  - android-26
env:
  global:
  - secure: b27erfqez9hITsNt2CwLZ0nqL6uKqVk8csXx/RRp9+5kNpWxyuolgUkROyu97OkEzqB5I8BHiIfjuyWcFY8sNh/MlRHreJVATAkUQqq2yYQ+o3aDYVJamIulAfiTbb2oPoYomGRXPITo7V+Vfch43UELxp+WrOCFKyzFY+34fs0scvhOz21kJKv3ks5hIV4I3vpTGAMc5pf68kJW9W3yaGyeRLlHjgj/hZW6i/srvANLip/GHiX7UqmA2XuOyvFHyuGCj3g2lDYZSzvYiEter+dQ+RfETd0aFCiJXSoFZQ2THeGTjOWKgAXvTIwejR16J2lL9q61aVKvL8XNt+eX/dcGmcdcW4JnG97u/SI5OJgd+2j9SWXMneeb+647OA4kzYesEMig7R0255KGueFLBQ3NWaLICBTZHTDJzpvysMylY7CDKzUrRWJxA0VCYJbBThAYohJcrTOFscuKwaKMjLd27BoRFT/OwWkbJXXulPic5jVfv9K42XG3H5gDzBN+5ByLqG0VH+sKPMVZlsNvjUvTq5zK4uhnnYOJoKOuMelZ/hJjgLuTfNEgzlJzqmJRA7Dn5QgRfIPPzsGz9F17U4RW5zk2Kar/Mof3si+19zSJqcqE62RVSAYCOv52dqcV1+s/RSps/tNIZ3hVAlxygntEh1bFZpKOjcTNptbiuH0=
  - secure: BhJ+jzagFPVzPputk2GZcPwQYguILWUWDMdU/5kcrtqKYRLViPLtwEoANuZQRe3kL5XP6+QpKB6QwPR6Qeph7D/sWScQ9dOEHIO5n2HMf7CH+8iEE3cNohyqwR9JZsszbKzdK+e9WS/vFHmSfRILN1/hl6ZMQpFig8eN0G0IwqpXGPnoqVAn3gEXRSuOA39Ybp/XocXI2W8e4uVdQjlnvkf9mcTgUw3vcq+373SqXjsDt+n77yrcr46STOYsDBv9WB2AHs3WMUtPwt6l3rlEvDPnYhNfY5LunKGsntG7RtYbKBhjkGSVfUs3IADePOcBgHXEsrL01vGcC1++dro8ANvMmt3mfRv4kQ+wJTFJbxZyTIJmh2Xs+Gk4pZrDZvfOgKiLj2zm9/PkIgOHXwuNdgFtDI2zv1h/mTF/ejJUaqfWSda12EO4DuGQ2pmF2l+Tf/KlnJdhJfdfb4OzSoMHBPXyA2kTz8rOmKWgunA9IoaXCikqTD/ctNccvWsyI8l7oybzt134XGVpJgc25mHbmGd1BuewlLigs+dEJ4PBm9+hv1hcqhL4jHUtJ5rwpNBKRSVKExxtZTW9cE/MkVeGpYKsT8fyDpPsizA0TuqmELr9pVNO3sjVU+ATAri8TBQGZoGk54b0CM/hxCG6tO1ejv16wd+TLapyOFlGFZW22lM=
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
before_install:
- yes | sdkmanager "platforms;android-27"
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
before_script:
- export VERSION_TO_BUILD="$TRAVIS_TAG"
install:
- bundle install
script:
- gpg --batch --passphrase u3zZs4F7XHC5y --output app/google-services.json --decrypt
  app/google-services.json.enc
- "./gradlew --stacktrace lintDevelopmentDebug"
- "./gradlew --stacktrace ktlintDevelopmentDebugCheck"
- bundle exec danger
deploy:
  provider: releases
  api_key: "$GITHUB_OAUTH_TOKEN"
  file: app/build/outputs/apk/app-${VERSION_TO_BUILD}-release.apk
  skip_cleanup: true
  on:
    tags: true
